// Generated by Qleany v1.5.0 from entity_controller.tera

use super::{
    dtos::{CreateInlineElementDto, InlineElementDto, UpdateInlineElementDto},
    units_of_work::{InlineElementReadUoWFactory, InlineElementWriteUoWFactory},
};
use anyhow::{Ok, Result};
use common::direct_access::use_cases;
use common::undo_redo::UndoRedoManager;
use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create_orphan(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &CreateInlineElementDto,
) -> Result<InlineElementDto> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::UndoableCreateOrphanUseCase::new(uow_factory);
    let entity_in: common::entities::InlineElement = entity.into();
    let result = uc.execute(&entity_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into())
}

pub fn create_orphan_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[CreateInlineElementDto],
) -> Result<Vec<InlineElementDto>> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::InlineElement> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UndoableCreateOrphanUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &CreateInlineElementDto,
    owner_id: EntityId,
    index: i32,
) -> Result<InlineElementDto> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::InlineElement = entity.into();
    let strategy = use_cases::OwnerStrategy::Appending;
    let mut uc = use_cases::UndoableCreateUseCase::new(uow_factory, strategy);
    let result = uc.execute(&entity_in, owner_id, index)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into())
}

pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[CreateInlineElementDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<InlineElementDto>> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::InlineElement> =
        entities.iter().map(|dto| dto.into()).collect();
    let strategy = use_cases::OwnerStrategy::Appending;
    let mut uc = use_cases::UndoableCreateUseCase::new(uow_factory, strategy);
    let result = uc.execute_multi(&entities_in, owner_id, index)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<InlineElementDto>> {
    let uow_factory = InlineElementReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute(id)?.map(|e| e.into()))
}

pub fn get_all(db_context: &DbContext) -> Result<Vec<InlineElementDto>> {
    let uow_factory = InlineElementReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute_all()?.into_iter().map(|e| e.into()).collect())
}

pub fn get_multi(
    db_context: &DbContext,
    ids: &[EntityId],
) -> Result<Vec<Option<InlineElementDto>>> {
    let uow_factory = InlineElementReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc
        .execute_multi(ids)?
        .into_iter()
        .map(|o| o.map(|e| e.into()))
        .collect())
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &UpdateInlineElementDto,
) -> Result<InlineElementDto> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::InlineElement = entity.into();
    let mut uc = use_cases::UndoableUpdateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into())
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[UpdateInlineElementDto],
) -> Result<Vec<InlineElementDto>> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::InlineElement> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UndoableUpdateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn update_with_relationships(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &InlineElementDto,
) -> Result<InlineElementDto> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::InlineElement = entity.into();
    let mut uc = use_cases::UndoableUpdateWithRelationshipsUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into())
}

pub fn update_with_relationships_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[InlineElementDto],
) -> Result<Vec<InlineElementDto>> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::InlineElement> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UndoableUpdateWithRelationshipsUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn remove(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    id: &EntityId,
) -> Result<()> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::UndoableRemoveUseCase::new(uow_factory);
    uc.execute(id)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = InlineElementWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::UndoableRemoveUseCase::new(uow_factory);
    uc.execute_multi(ids)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}
