[package]
name = "text-document"
version = "0.0.5"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Cyril Jacquet <cyril.jacquet@skribisto.eu>"]
repository = "https://github.com/jacquetc/text-document"
readme = "README.md"
documentation = "https://docs.rs/text-document/"
description = """
Text document structure and management.
"""
keywords = ["text", "document", "model","format"]
categories = ["data-structures", "text-editors", "text-processing", "parsing"]


[dependencies]
controller = { path = "controller" }