// Generated by Qleany v1.7.3 from common_entity_table.tera
// Phase 2 step 6: junction-free. `Table.cells` is the source of
// truth; the jn_table_cell_from_table_cells table and the
// `hydrate()` re-population step are gone.

use crate::database::Store;
use crate::entities::Table;
use crate::error::RepositoryError;
use crate::types::EntityId;
use std::collections::HashMap as StdHashMap;

use super::table_repository::TableRelationshipField;
use super::table_repository::TableTable;
use super::table_repository::TableTableRO;

fn read_field(table: &Table, field: &TableRelationshipField) -> Vec<EntityId> {
    match field {
        TableRelationshipField::Cells => table.cells.clone(),
    }
}

fn write_field(table: &mut Table, field: &TableRelationshipField, ids: Vec<EntityId>) {
    match field {
        TableRelationshipField::Cells => table.cells = ids,
    }
}

pub struct TableHashMapTable<'a> {
    store: &'a Store,
}

impl<'a> TableHashMapTable<'a> {
    pub fn new(store: &'a Store) -> Self {
        Self { store }
    }
}

impl<'a> TableTable for TableHashMapTable<'a> {
    fn create(&mut self, entity: &Table) -> Result<Table, RepositoryError> {
        self.create_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    fn create_multi(&mut self, entities: &[Table]) -> Result<Vec<Table>, RepositoryError> {
        let mut created = Vec::with_capacity(entities.len());
        let mut table_map = self.store.tables.write().unwrap();

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                let id = self.store.next_id("table");
                Table {
                    id,
                    ..entity.clone()
                }
            } else {
                if table_map.contains_key(&entity.id) {
                    return Err(RepositoryError::DuplicateId {
                        entity: "Table",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            table_map.insert(new_entity.id, new_entity.clone());
            created.push(new_entity);
        }
        Ok(created)
    }

    fn get(&self, id: &EntityId) -> Result<Option<Table>, RepositoryError> {
        Ok(self.store.tables.read().unwrap().get(id).cloned())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Table>>, RepositoryError> {
        let map = self.store.tables.read().unwrap();
        Ok(ids.iter().map(|id| map.get(id).cloned()).collect())
    }

    fn get_all(&self) -> Result<Vec<Table>, RepositoryError> {
        Ok(self.store.tables.read().unwrap().values().cloned().collect())
    }

    fn update(&mut self, entity: &Table) -> Result<Table, RepositoryError> {
        self.update_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    fn update_multi(&mut self, entities: &[Table]) -> Result<Vec<Table>, RepositoryError> {
        let mut table_map = self.store.tables.write().unwrap();
        let mut result = Vec::with_capacity(entities.len());
        for entity in entities {
            let mut to_write = entity.clone();
            if let Some(existing) = table_map.get(&entity.id) {
                to_write.cells = existing.cells.clone();
            }
            table_map.insert(entity.id, to_write.clone());
            result.push(to_write);
        }
        Ok(result)
    }

    fn update_with_relationships(&mut self, entity: &Table) -> Result<Table, RepositoryError> {
        self.update_with_relationships_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[Table],
    ) -> Result<Vec<Table>, RepositoryError> {
        let mut table_map = self.store.tables.write().unwrap();
        let mut result = Vec::with_capacity(entities.len());
        for entity in entities {
            table_map.insert(entity.id, entity.clone());
            result.push(entity.clone());
        }
        Ok(result)
    }

    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let removed: std::collections::HashSet<EntityId> = ids.iter().copied().collect();

        {
            let mut table_map = self.store.tables.write().unwrap();
            for id in ids {
                table_map.remove(id);
            }
        }

        // Backward cleanup:
        // 1. Documents whose `tables` Vec listed a removed Table.
        {
            let mut doc_map = self.store.documents.write().unwrap();
            let updates: Vec<(EntityId, crate::entities::Document)> = doc_map
                .iter()
                .filter_map(|(did, d)| {
                    if d.tables.iter().any(|tid| removed.contains(tid)) {
                        let mut updated = d.clone();
                        updated.tables.retain(|tid| !removed.contains(tid));
                        Some((*did, updated))
                    } else {
                        None
                    }
                })
                .collect();
            for (did, d) in updates {
                doc_map.insert(did, d);
            }
        }

        // 2. Frames whose `table` Option pointed at a removed Table.
        {
            let mut frame_map = self.store.frames.write().unwrap();
            let updates: Vec<(EntityId, crate::entities::Frame)> = frame_map
                .iter()
                .filter_map(|(fid, f)| {
                    f.table.filter(|t| removed.contains(t)).map(|_| {
                        let mut updated = f.clone();
                        updated.table = None;
                        (*fid, updated)
                    })
                })
                .collect();
            for (fid, f) in updates {
                frame_map.insert(fid, f);
            }
        }

        Ok(())
    }

    fn get_relationship(
        &self,
        id: &EntityId,
        field: &TableRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        Ok(self
            .store
            .tables
            .read()
            .unwrap()
            .get(id)
            .map(|t| read_field(t, field))
            .unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &TableRelationshipField,
    ) -> Result<StdHashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let map = self.store.tables.read().unwrap();
        let mut out = StdHashMap::new();
        for id in ids {
            out.insert(
                *id,
                map.get(id).map(|t| read_field(t, field)).unwrap_or_default(),
            );
        }
        Ok(out)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &TableRelationshipField,
    ) -> Result<usize, RepositoryError> {
        Ok(self
            .store
            .tables
            .read()
            .unwrap()
            .get(id)
            .map(|t| read_field(t, field).len())
            .unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &TableRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        Ok(self
            .store
            .tables
            .read()
            .unwrap()
            .get(id)
            .map(|t| read_field(t, field).into_iter().skip(offset).take(limit).collect())
            .unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &TableRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let map = self.store.tables.read().unwrap();
        let mut out = Vec::new();
        for (id, table) in map.iter() {
            let list = read_field(table, field);
            if right_ids.iter().any(|rid| list.contains(rid)) {
                out.push((*id, list));
            }
        }
        Ok(out)
    }

    fn set_relationship_multi(
        &mut self,
        field: &TableRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), RepositoryError> {
        let mut map = self.store.tables.write().unwrap();
        for (id, ids) in relationships {
            if let Some(table) = map.get_mut(&id) {
                write_field(table, field, ids);
            }
        }
        Ok(())
    }

    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &TableRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let mut map = self.store.tables.write().unwrap();
        if let Some(table) = map.get_mut(id) {
            write_field(table, field, right_ids.to_vec());
        }
        Ok(())
    }

    fn move_relationship_ids(
        &mut self,
        id: &EntityId,
        field: &TableRelationshipField,
        ids_to_move: &[EntityId],
        new_index: i32,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let mut map = self.store.tables.write().unwrap();
        let Some(table) = map.get_mut(id) else {
            return Ok(Vec::new());
        };
        let current = read_field(table, field);
        let moved = reorder(current, ids_to_move, new_index);
        write_field(table, field, moved.clone());
        Ok(moved)
    }
}

pub struct TableHashMapTableRO<'a> {
    store: &'a Store,
}

impl<'a> TableHashMapTableRO<'a> {
    pub fn new(store: &'a Store) -> Self {
        Self { store }
    }
}

impl<'a> TableTableRO for TableHashMapTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Table>, RepositoryError> {
        Ok(self.store.tables.read().unwrap().get(id).cloned())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Table>>, RepositoryError> {
        let map = self.store.tables.read().unwrap();
        Ok(ids.iter().map(|id| map.get(id).cloned()).collect())
    }

    fn get_all(&self) -> Result<Vec<Table>, RepositoryError> {
        Ok(self.store.tables.read().unwrap().values().cloned().collect())
    }

    fn get_relationship(
        &self,
        id: &EntityId,
        field: &TableRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        Ok(self
            .store
            .tables
            .read()
            .unwrap()
            .get(id)
            .map(|t| read_field(t, field))
            .unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &TableRelationshipField,
    ) -> Result<StdHashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let map = self.store.tables.read().unwrap();
        let mut out = StdHashMap::new();
        for id in ids {
            out.insert(
                *id,
                map.get(id).map(|t| read_field(t, field)).unwrap_or_default(),
            );
        }
        Ok(out)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &TableRelationshipField,
    ) -> Result<usize, RepositoryError> {
        Ok(self
            .store
            .tables
            .read()
            .unwrap()
            .get(id)
            .map(|t| read_field(t, field).len())
            .unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &TableRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        Ok(self
            .store
            .tables
            .read()
            .unwrap()
            .get(id)
            .map(|t| read_field(t, field).into_iter().skip(offset).take(limit).collect())
            .unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &TableRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let map = self.store.tables.read().unwrap();
        let mut out = Vec::new();
        for (id, table) in map.iter() {
            let list = read_field(table, field);
            if right_ids.iter().any(|rid| list.contains(rid)) {
                out.push((*id, list));
            }
        }
        Ok(out)
    }
}

fn reorder(current: Vec<EntityId>, ids_to_move: &[EntityId], new_index: i32) -> Vec<EntityId> {
    if ids_to_move.is_empty() {
        return current;
    }
    let move_set: std::collections::HashSet<EntityId> = ids_to_move.iter().copied().collect();
    let mut remaining: Vec<EntityId> = current
        .into_iter()
        .filter(|eid| !move_set.contains(eid))
        .collect();
    let insert_pos = if new_index < 0 || (new_index as usize) > remaining.len() {
        remaining.len()
    } else {
        new_index as usize
    };
    for (i, &eid) in ids_to_move.iter().enumerate() {
        remaining.insert(insert_pos + i, eid);
    }
    remaining
}
