// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::FindResultDto;
use crate::FindTextDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::direct_access::document::document_repository::DocumentRelationshipField;
use common::direct_access::frame::frame_repository::FrameRelationshipField;
use common::direct_access::root::root_repository::RootRelationshipField;
use common::entities::{Block, Document, Frame, InlineElement, Root};
use common::types::EntityId;
use regex::Regex;

pub trait FindTextUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn FindTextUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "Root", action = "GetRO")]
#[macros::uow_action(entity = "Root", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Document", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Frame", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Block", action = "GetMultiRO")]
pub trait FindTextUnitOfWorkTrait: QueryUnitOfWork {}

/// Build the full document text by concatenating block plain_text with '\n' separators.
/// Returns the full text string.
fn build_full_text(uow: &dyn FindTextUnitOfWorkTrait) -> Result<String> {
    let root = uow
        .get_root(&1)?
        .ok_or_else(|| anyhow!("Root entity not found"))?;

    let doc_ids = uow.get_root_relationship(&root.id, &RootRelationshipField::Document)?;
    let doc_id = *doc_ids
        .first()
        .ok_or_else(|| anyhow!("Root has no document"))?;

    let frame_ids =
        uow.get_document_relationship(&doc_id, &DocumentRelationshipField::Frames)?;

    let mut all_block_ids: Vec<EntityId> = Vec::new();
    for frame_id in &frame_ids {
        let block_ids =
            uow.get_frame_relationship(frame_id, &FrameRelationshipField::Blocks)?;
        all_block_ids.extend(block_ids);
    }

    let blocks_opt = uow.get_block_multi(&all_block_ids)?;
    let mut blocks: Vec<Block> = blocks_opt.into_iter().filter_map(|b| b).collect();
    blocks.sort_by_key(|b| b.document_position);

    let full_text = blocks
        .iter()
        .map(|b| b.plain_text.as_str())
        .collect::<Vec<&str>>()
        .join("\n");

    Ok(full_text)
}

/// Check if the given char index in the text is a word boundary.
/// Uses Unicode-aware `is_alphanumeric()`.
fn is_word_boundary(text: &str, char_idx: usize) -> bool {
    let chars: Vec<char> = text.chars().collect();
    if char_idx == 0 || char_idx >= chars.len() {
        return true;
    }
    let ch = chars[char_idx];
    !ch.is_alphanumeric() && ch != '_'
}

/// Find all occurrences of the query in the text, respecting search options.
/// All positions are in char indices (not byte offsets).
/// Returns a vec of (char_position, char_length) for each match.
fn find_all_matches(
    full_text: &str,
    query: &str,
    case_sensitive: bool,
    whole_word: bool,
    use_regex: bool,
) -> Result<Vec<(usize, usize)>> {
    if query.is_empty() {
        return Ok(Vec::new());
    }

    let mut results = Vec::new();

    if use_regex {
        // Build regex with case-insensitive flag if needed
        let pattern = if case_sensitive {
            query.to_string()
        } else {
            format!("(?i){}", query)
        };
        let re = Regex::new(&pattern)
            .map_err(|e| anyhow!("Invalid regex pattern: {}", e))?;

        // Regex::find_iter returns byte-based Match objects.
        // We need to convert byte offsets to char offsets.
        let char_offsets = build_byte_to_char_map(full_text);

        for mat in re.find_iter(full_text) {
            let char_start = char_offsets[mat.start()];
            let char_end = char_offsets[mat.end()];
            let char_len = char_end - char_start;

            if whole_word {
                if is_word_boundary(full_text, char_start)
                    && is_word_boundary(full_text, char_end)
                {
                    results.push((char_start, char_len));
                }
            } else {
                results.push((char_start, char_len));
            }
        }
    } else {
        // Literal string search using char-based scanning
        let text_chars: Vec<char> = full_text.chars().collect();
        let (search_chars, query_chars) = if case_sensitive {
            (text_chars.clone(), query.chars().collect::<Vec<char>>())
        } else {
            (
                text_chars.iter().map(|c| c.to_lowercase().next().unwrap_or(*c)).collect::<Vec<char>>(),
                query.chars().map(|c| c.to_lowercase().next().unwrap_or(c)).collect::<Vec<char>>(),
            )
        };

        let query_char_len = query_chars.len();
        let mut pos = 0;
        while pos + query_char_len <= search_chars.len() {
            if search_chars[pos..pos + query_char_len] == query_chars[..] {
                if whole_word {
                    // Check word boundary using original text chars
                    let before_ok = pos == 0 || {
                        let ch = text_chars[pos - 1];
                        !ch.is_alphanumeric() && ch != '_'
                    };
                    let after_ok = pos + query_char_len >= text_chars.len() || {
                        let ch = text_chars[pos + query_char_len];
                        !ch.is_alphanumeric() && ch != '_'
                    };
                    if before_ok && after_ok {
                        results.push((pos, query_char_len));
                    }
                } else {
                    results.push((pos, query_char_len));
                }
                pos += 1;
            } else {
                pos += 1;
            }
        }
    }

    Ok(results)
}

/// Build a mapping from byte offset to char index for a string.
/// byte_to_char[byte_offset] = char_index
/// The vec has len = text.len() + 1 (inclusive of the end position).
fn build_byte_to_char_map(text: &str) -> Vec<usize> {
    let mut map = vec![0usize; text.len() + 1];
    let mut char_idx = 0;
    for (byte_idx, _) in text.char_indices() {
        map[byte_idx] = char_idx;
        char_idx += 1;
    }
    map[text.len()] = char_idx;
    map
}

pub struct FindTextUseCase {
    uow_factory: Box<dyn FindTextUnitOfWorkFactoryTrait>,
}

impl FindTextUseCase {
    pub fn new(uow_factory: Box<dyn FindTextUnitOfWorkFactoryTrait>) -> Self {
        FindTextUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &FindTextDto) -> Result<FindResultDto> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        let full_text = build_full_text(uow.as_ref())?;

        let all_matches = find_all_matches(
            &full_text,
            &dto.query,
            dto.case_sensitive,
            dto.whole_word,
            dto.use_regex,
        )?;

        let start_pos = dto.start_position.max(0) as usize;

        let result = if dto.search_backward {
            all_matches
                .iter()
                .rev()
                .find(|(pos, _)| *pos < start_pos)
                .copied()
        } else {
            all_matches
                .iter()
                .find(|(pos, _)| *pos >= start_pos)
                .copied()
        };

        uow.end_transaction()?;

        match result {
            Some((pos, len)) => Ok(FindResultDto {
                found: true,
                position: pos as i64,
                length: len as i64,
            }),
            None => Ok(FindResultDto {
                found: false,
                position: 0,
                length: 0,
            }),
        }
    }
}
