// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::SetBlockFormatDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Block, Document};
use common::types::EntityId;

pub trait SetBlockFormatUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn SetBlockFormatUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update, UpdateMulti, remove,
// removeMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/set_block_format_uow.rs
//
#[macros::uow_action(entity = "Document", action = "Get")]
#[macros::uow_action(entity = "Document", action = "GetMulti")]
#[macros::uow_action(entity = "Document", action = "Snapshot")]
#[macros::uow_action(entity = "Document", action = "Restore")]
#[macros::uow_action(entity = "Block", action = "Get")]
#[macros::uow_action(entity = "Block", action = "GetMulti")]
#[macros::uow_action(entity = "Block", action = "Snapshot")]
#[macros::uow_action(entity = "Block", action = "Restore")]
pub trait SetBlockFormatUnitOfWorkTrait: CommandUnitOfWork {}

pub struct SetBlockFormatUseCase {
    uow_factory: Box<dyn SetBlockFormatUnitOfWorkFactoryTrait>,
}

impl SetBlockFormatUseCase {
    pub fn new(uow_factory: Box<dyn SetBlockFormatUnitOfWorkFactoryTrait>) -> Self {
        SetBlockFormatUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &SetBlockFormatDto) -> Result<()> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: SetBlockFormatUseCase to be implemented
        unimplemented!("SetBlockFormatUseCase unimplemented");
        uow.commit()?;
        Ok(())
    }
}
use common::undo_redo::UndoRedoCommand;
use std::any::Any;
impl UndoRedoCommand for SetBlockFormatUseCase {
    fn undo(&mut self) -> Result<()> {
        //TODO: SetBlockFormatUseCase  undo to be implemented
        unimplemented!("SetBlockFormatUseCase undo unimplemented");

        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        //TODO: SetBlockFormatUseCase  redo to be implemented
        unimplemented!("SetBlockFormatUseCase redo unimplemented");

        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
