// Generated by Qleany v1.5.1 from direct_access_lib.tera

// Allow too_many_arguments for Qleany-generated controller functions
// (move_relationship takes db_context, event_hub, undo_redo_manager,
// stack_id, id, field, ids_to_move, new_index).
#![allow(clippy::too_many_arguments)]

// This file defines the direct_access crate public API.

// Project entities (auto-listed)

// Root
pub mod root;

// Document
pub mod document;

// Frame
pub mod frame;

// Block
pub mod block;

// InlineElement
pub mod inline_element;

// List
pub mod list;

// Resource
pub mod resource;

// Table
pub mod table;

// TableCell
pub mod table_cell;

// Re-exports for all project entities

pub use root::dtos::*;
pub use root::root_controller;

pub use document::document_controller;
pub use document::dtos::*;

pub use frame::dtos::*;
pub use frame::frame_controller;

pub use block::block_controller;
pub use block::dtos::*;

pub use inline_element::dtos::*;
pub use inline_element::inline_element_controller;

pub use list::dtos::*;
pub use list::list_controller;

pub use resource::dtos::*;
pub use resource::resource_controller;

pub use table::dtos::*;
pub use table::table_controller;

pub use table_cell::dtos::*;
pub use table_cell::table_cell_controller;
