// Generated by Qleany v1.7.3 from common_entity_table.tera
// Phase 2 step 6: junction-free. `TableCell.cell_frame` is the
// source of truth; the jn_frame_from_table_cell_cell_frame table and
// the `hydrate()` re-population step are gone.

use crate::database::hashmap_store::HashMapStore;
use crate::entities::TableCell;
use crate::error::RepositoryError;
use crate::types::EntityId;
use std::collections::HashMap as StdHashMap;

use super::table_cell_repository::TableCellRelationshipField;
use super::table_cell_repository::TableCellTable;
use super::table_cell_repository::TableCellTableRO;

fn read_field(cell: &TableCell, field: &TableCellRelationshipField) -> Vec<EntityId> {
    match field {
        TableCellRelationshipField::CellFrame => cell.cell_frame.into_iter().collect(),
    }
}

fn write_field(cell: &mut TableCell, field: &TableCellRelationshipField, ids: Vec<EntityId>) {
    match field {
        TableCellRelationshipField::CellFrame => cell.cell_frame = ids.first().copied(),
    }
}

pub struct TableCellHashMapTable<'a> {
    store: &'a HashMapStore,
}

impl<'a> TableCellHashMapTable<'a> {
    pub fn new(store: &'a HashMapStore) -> Self {
        Self { store }
    }
}

impl<'a> TableCellTable for TableCellHashMapTable<'a> {
    fn create(&mut self, entity: &TableCell) -> Result<TableCell, RepositoryError> {
        self.create_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    fn create_multi(&mut self, entities: &[TableCell]) -> Result<Vec<TableCell>, RepositoryError> {
        let mut created = Vec::with_capacity(entities.len());
        let mut map = self.store.table_cells.write().unwrap();

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                let id = self.store.next_id("table_cell");
                TableCell {
                    id,
                    ..entity.clone()
                }
            } else {
                if map.contains_key(&entity.id) {
                    return Err(RepositoryError::DuplicateId {
                        entity: "TableCell",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            map.insert(new_entity.id, new_entity.clone());
            created.push(new_entity);
        }
        Ok(created)
    }

    fn get(&self, id: &EntityId) -> Result<Option<TableCell>, RepositoryError> {
        Ok(self.store.table_cells.read().unwrap().get(id).cloned())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<TableCell>>, RepositoryError> {
        let map = self.store.table_cells.read().unwrap();
        Ok(ids.iter().map(|id| map.get(id).cloned()).collect())
    }

    fn get_all(&self) -> Result<Vec<TableCell>, RepositoryError> {
        Ok(self.store.table_cells.read().unwrap().values().cloned().collect())
    }

    fn update(&mut self, entity: &TableCell) -> Result<TableCell, RepositoryError> {
        self.update_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    fn update_multi(&mut self, entities: &[TableCell]) -> Result<Vec<TableCell>, RepositoryError> {
        let mut map = self.store.table_cells.write().unwrap();
        let mut result = Vec::with_capacity(entities.len());
        for entity in entities {
            let mut to_write = entity.clone();
            if let Some(existing) = map.get(&entity.id) {
                to_write.cell_frame = existing.cell_frame;
            }
            map.insert(entity.id, to_write.clone());
            result.push(to_write);
        }
        Ok(result)
    }

    fn update_with_relationships(
        &mut self,
        entity: &TableCell,
    ) -> Result<TableCell, RepositoryError> {
        self.update_with_relationships_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[TableCell],
    ) -> Result<Vec<TableCell>, RepositoryError> {
        let mut map = self.store.table_cells.write().unwrap();
        let mut result = Vec::with_capacity(entities.len());
        for entity in entities {
            map.insert(entity.id, entity.clone());
            result.push(entity.clone());
        }
        Ok(result)
    }

    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let removed: std::collections::HashSet<EntityId> = ids.iter().copied().collect();

        {
            let mut map = self.store.table_cells.write().unwrap();
            for id in ids {
                map.remove(id);
            }
        }

        // Backward cleanup: Tables whose `cells` Vec listed any
        // removed TableCell must strip those ids.
        {
            let mut table_map = self.store.tables.write().unwrap();
            let updates: Vec<(EntityId, crate::entities::Table)> = table_map
                .iter()
                .filter_map(|(tid, t)| {
                    if t.cells.iter().any(|cid| removed.contains(cid)) {
                        let mut updated = t.clone();
                        updated.cells.retain(|cid| !removed.contains(cid));
                        Some((*tid, updated))
                    } else {
                        None
                    }
                })
                .collect();
            for (tid, t) in updates {
                table_map.insert(tid, t);
            }
        }

        Ok(())
    }

    fn get_relationship(
        &self,
        id: &EntityId,
        field: &TableCellRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        Ok(self
            .store
            .table_cells
            .read()
            .unwrap()
            .get(id)
            .map(|c| read_field(c, field))
            .unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &TableCellRelationshipField,
    ) -> Result<StdHashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let map = self.store.table_cells.read().unwrap();
        let mut out = StdHashMap::new();
        for id in ids {
            out.insert(
                *id,
                map.get(id).map(|c| read_field(c, field)).unwrap_or_default(),
            );
        }
        Ok(out)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &TableCellRelationshipField,
    ) -> Result<usize, RepositoryError> {
        Ok(self
            .store
            .table_cells
            .read()
            .unwrap()
            .get(id)
            .map(|c| read_field(c, field).len())
            .unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &TableCellRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        Ok(self
            .store
            .table_cells
            .read()
            .unwrap()
            .get(id)
            .map(|c| read_field(c, field).into_iter().skip(offset).take(limit).collect())
            .unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &TableCellRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let map = self.store.table_cells.read().unwrap();
        let mut out = Vec::new();
        for (id, cell) in map.iter() {
            let list = read_field(cell, field);
            if right_ids.iter().any(|rid| list.contains(rid)) {
                out.push((*id, list));
            }
        }
        Ok(out)
    }

    fn set_relationship_multi(
        &mut self,
        field: &TableCellRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), RepositoryError> {
        let mut map = self.store.table_cells.write().unwrap();
        for (id, ids) in relationships {
            if let Some(cell) = map.get_mut(&id) {
                write_field(cell, field, ids);
            }
        }
        Ok(())
    }

    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &TableCellRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let mut map = self.store.table_cells.write().unwrap();
        if let Some(cell) = map.get_mut(id) {
            write_field(cell, field, right_ids.to_vec());
        }
        Ok(())
    }

    fn move_relationship_ids(
        &mut self,
        id: &EntityId,
        field: &TableCellRelationshipField,
        ids_to_move: &[EntityId],
        new_index: i32,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let mut map = self.store.table_cells.write().unwrap();
        let Some(cell) = map.get_mut(id) else {
            return Ok(Vec::new());
        };
        let current = read_field(cell, field);
        let moved = reorder(current, ids_to_move, new_index);
        write_field(cell, field, moved.clone());
        Ok(moved)
    }
}

pub struct TableCellHashMapTableRO<'a> {
    store: &'a HashMapStore,
}

impl<'a> TableCellHashMapTableRO<'a> {
    pub fn new(store: &'a HashMapStore) -> Self {
        Self { store }
    }
}

impl<'a> TableCellTableRO for TableCellHashMapTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<TableCell>, RepositoryError> {
        Ok(self.store.table_cells.read().unwrap().get(id).cloned())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<TableCell>>, RepositoryError> {
        let map = self.store.table_cells.read().unwrap();
        Ok(ids.iter().map(|id| map.get(id).cloned()).collect())
    }

    fn get_all(&self) -> Result<Vec<TableCell>, RepositoryError> {
        Ok(self.store.table_cells.read().unwrap().values().cloned().collect())
    }

    fn get_relationship(
        &self,
        id: &EntityId,
        field: &TableCellRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        Ok(self
            .store
            .table_cells
            .read()
            .unwrap()
            .get(id)
            .map(|c| read_field(c, field))
            .unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &TableCellRelationshipField,
    ) -> Result<StdHashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let map = self.store.table_cells.read().unwrap();
        let mut out = StdHashMap::new();
        for id in ids {
            out.insert(
                *id,
                map.get(id).map(|c| read_field(c, field)).unwrap_or_default(),
            );
        }
        Ok(out)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &TableCellRelationshipField,
    ) -> Result<usize, RepositoryError> {
        Ok(self
            .store
            .table_cells
            .read()
            .unwrap()
            .get(id)
            .map(|c| read_field(c, field).len())
            .unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &TableCellRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        Ok(self
            .store
            .table_cells
            .read()
            .unwrap()
            .get(id)
            .map(|c| read_field(c, field).into_iter().skip(offset).take(limit).collect())
            .unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &TableCellRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let map = self.store.table_cells.read().unwrap();
        let mut out = Vec::new();
        for (id, cell) in map.iter() {
            let list = read_field(cell, field);
            if right_ids.iter().any(|rid| list.contains(rid)) {
                out.push((*id, list));
            }
        }
        Ok(out)
    }
}

fn reorder(current: Vec<EntityId>, ids_to_move: &[EntityId], new_index: i32) -> Vec<EntityId> {
    if ids_to_move.is_empty() {
        return current;
    }
    let move_set: std::collections::HashSet<EntityId> = ids_to_move.iter().copied().collect();
    let mut remaining: Vec<EntityId> = current
        .into_iter()
        .filter(|eid| !move_set.contains(eid))
        .collect();
    let insert_pos = if new_index < 0 || (new_index as usize) > remaining.len() {
        remaining.len()
    } else {
        new_index as usize
    };
    for (i, &eid) in ids_to_move.iter().enumerate() {
        remaining.insert(insert_pos + i, eid);
    }
    remaining
}
