// Generated by Qleany v1.4.8 from entity_dtos.tera

use common::entities::List;
use common::entities::ListStyle;
use common::types::EntityId;
use serde::{Deserialize, Serialize};
use std::convert::From;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ListDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub style: ListStyle,
    pub indent: i64,
    pub prefix: String,
    pub suffix: String,
}

impl From<ListDto> for List {
    fn from(dto: ListDto) -> Self {
        List {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            style: dto.style,
            indent: dto.indent,
            prefix: dto.prefix,
            suffix: dto.suffix,
        }
    }
}

impl From<&ListDto> for List {
    fn from(dto: &ListDto) -> Self {
        List {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            style: dto.style.clone(),
            indent: dto.indent.clone(),
            prefix: dto.prefix.clone(),
            suffix: dto.suffix.clone(),
        }
    }
}

impl From<List> for ListDto {
    fn from(entity: List) -> Self {
        ListDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            style: entity.style,
            indent: entity.indent,
            prefix: entity.prefix,
            suffix: entity.suffix,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateListDto {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub style: ListStyle,
    pub indent: i64,
    pub prefix: String,
    pub suffix: String,
}

impl From<CreateListDto> for List {
    fn from(dto: CreateListDto) -> Self {
        List {
            id: 0,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            style: dto.style,
            indent: dto.indent,
            prefix: dto.prefix,
            suffix: dto.suffix,
        }
    }
}

impl From<&CreateListDto> for List {
    fn from(dto: &CreateListDto) -> Self {
        List {
            id: 0,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            style: dto.style.clone(),
            indent: dto.indent.clone(),
            prefix: dto.prefix.clone(),
            suffix: dto.suffix.clone(),
        }
    }
}

impl From<List> for CreateListDto {
    fn from(entity: List) -> Self {
        CreateListDto {
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            style: entity.style,
            indent: entity.indent,
            prefix: entity.prefix,
            suffix: entity.suffix,
        }
    }
}
