// Generated by Qleany v1.4.8 from feature_units_of_work_mod.tera

pub(crate) mod merge_text_format_uow;
pub(crate) mod set_block_format_uow;
pub(crate) mod set_frame_format_uow;
pub(crate) mod set_text_format_uow;
