// Generated by Qleany v1.4.8 from feature_controller.tera

use crate::CreateListDto;
use crate::CreateListResultDto;
use crate::DeleteTextDto;
use crate::DeleteTextResultDto;
use crate::InsertBlockDto;
use crate::InsertBlockResultDto;
use crate::InsertFormattedTextDto;
use crate::InsertFormattedTextResultDto;
use crate::InsertFragmentDto;
use crate::InsertFragmentResultDto;
use crate::InsertFrameDto;
use crate::InsertFrameResultDto;
use crate::InsertHtmlAtPositionDto;
use crate::InsertHtmlAtPositionResultDto;
use crate::InsertImageDto;
use crate::InsertImageResultDto;
use crate::InsertListDto;
use crate::InsertListResultDto;
use crate::InsertMarkdownAtPositionDto;
use crate::InsertMarkdownAtPositionResultDto;
use crate::InsertTextDto;
use crate::InsertTextResultDto;
use crate::units_of_work::create_list_uow::CreateListUnitOfWorkFactory;
use crate::units_of_work::delete_text_uow::DeleteTextUnitOfWorkFactory;
use crate::units_of_work::insert_block_uow::InsertBlockUnitOfWorkFactory;
use crate::units_of_work::insert_formatted_text_uow::InsertFormattedTextUnitOfWorkFactory;
use crate::units_of_work::insert_fragment_uow::InsertFragmentUnitOfWorkFactory;
use crate::units_of_work::insert_frame_uow::InsertFrameUnitOfWorkFactory;
use crate::units_of_work::insert_html_at_position_uow::InsertHtmlAtPositionUnitOfWorkFactory;
use crate::units_of_work::insert_image_uow::InsertImageUnitOfWorkFactory;
use crate::units_of_work::insert_list_uow::InsertListUnitOfWorkFactory;
use crate::units_of_work::insert_markdown_at_position_uow::InsertMarkdownAtPositionUnitOfWorkFactory;
use crate::units_of_work::insert_text_uow::InsertTextUnitOfWorkFactory;
use crate::use_cases::create_list_uc::CreateListUseCase;
use crate::use_cases::delete_text_uc::DeleteTextUseCase;
use crate::use_cases::insert_block_uc::InsertBlockUseCase;
use crate::use_cases::insert_formatted_text_uc::InsertFormattedTextUseCase;
use crate::use_cases::insert_fragment_uc::InsertFragmentUseCase;
use crate::use_cases::insert_frame_uc::InsertFrameUseCase;
use crate::use_cases::insert_html_at_position_uc::InsertHtmlAtPositionUseCase;
use crate::use_cases::insert_image_uc::InsertImageUseCase;
use crate::use_cases::insert_list_uc::InsertListUseCase;
use crate::use_cases::insert_markdown_at_position_uc::InsertMarkdownAtPositionUseCase;
use crate::use_cases::insert_text_uc::InsertTextUseCase;
use anyhow::Result;
use common::event::{Event, Origin};

use common::event::DocumentEditingEvent::CreateList;
use common::event::DocumentEditingEvent::DeleteText;
use common::event::DocumentEditingEvent::InsertBlock;
use common::event::DocumentEditingEvent::InsertFormattedText;
use common::event::DocumentEditingEvent::InsertFragment;
use common::event::DocumentEditingEvent::InsertFrame;
use common::event::DocumentEditingEvent::InsertHtmlAtPosition;
use common::event::DocumentEditingEvent::InsertImage;
use common::event::DocumentEditingEvent::InsertList;
use common::event::DocumentEditingEvent::InsertMarkdownAtPosition;
use common::event::DocumentEditingEvent::InsertText;

use common::undo_redo::UndoRedoManager;
use common::{database::db_context::DbContext, event::EventHub};
use std::sync::Arc;

pub fn insert_text(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertTextDto,
) -> Result<InsertTextResultDto> {
    let uow_context = InsertTextUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertTextUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertText),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn delete_text(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &DeleteTextDto,
) -> Result<DeleteTextResultDto> {
    let uow_context = DeleteTextUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = DeleteTextUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(DeleteText),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn insert_block(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertBlockDto,
) -> Result<InsertBlockResultDto> {
    let uow_context = InsertBlockUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertBlockUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertBlock),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn insert_image(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertImageDto,
) -> Result<InsertImageResultDto> {
    let uow_context = InsertImageUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertImageUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertImage),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn insert_frame(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertFrameDto,
) -> Result<InsertFrameResultDto> {
    let uow_context = InsertFrameUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertFrameUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertFrame),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn insert_formatted_text(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertFormattedTextDto,
) -> Result<InsertFormattedTextResultDto> {
    let uow_context = InsertFormattedTextUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertFormattedTextUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertFormattedText),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn create_list(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &CreateListDto,
) -> Result<CreateListResultDto> {
    let uow_context = CreateListUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateListUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(CreateList),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn insert_list(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertListDto,
) -> Result<InsertListResultDto> {
    let uow_context = InsertListUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertListUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertList),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn insert_fragment(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertFragmentDto,
) -> Result<InsertFragmentResultDto> {
    let uow_context = InsertFragmentUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertFragmentUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertFragment),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn insert_html_at_position(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertHtmlAtPositionDto,
) -> Result<InsertHtmlAtPositionResultDto> {
    let uow_context = InsertHtmlAtPositionUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertHtmlAtPositionUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertHtmlAtPosition),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn insert_markdown_at_position(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &InsertMarkdownAtPositionDto,
) -> Result<InsertMarkdownAtPositionResultDto> {
    let uow_context = InsertMarkdownAtPositionUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = InsertMarkdownAtPositionUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::DocumentEditing(InsertMarkdownAtPosition),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}
