// Generated by Qleany v1.7.3 from common_entity_table.tera

// ═══════════════════════════════════════════════════════════════════════
// Leaf entity (no forward relationships) — macro implementation
// ═══════════════════════════════════════════════════════════════════════

use super::resource_repository::ResourceTable;
use super::resource_repository::ResourceTableRO;
use crate::entities::Resource;
use crate::error::RepositoryError;
use crate::types::EntityId;

crate::impl_leaf_entity_table!(
    entity: Resource,
    entity_name: "resource",
    store_field: resources,
    table_trait: ResourceTable,
    table_ro_trait: ResourceTableRO,
    table_struct: ResourceHashMapTable,
    table_ro_struct: ResourceHashMapTableRO,
    backward_junctions: [

        (jn_resource_from_document_resources),
    ],
);
