// Generated by Qleany v1.5.1 from feature_dtos.tera

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentStatsDto {
    pub character_count: i64,
    pub word_count: i64,
    pub block_count: i64,
    pub frame_count: i64,
    pub image_count: i64,
    pub list_count: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTextAtPositionDto {
    pub position: i64,
    pub length: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TextAtPositionDto {
    pub text: String,
    pub block_id: i64,
    pub element_id: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBlockAtPositionDto {
    pub position: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockInfoDto {
    pub block_id: i64,
    pub block_start: i64,
    pub block_length: i64,
    pub block_number: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExtractFragmentDto {
    pub position: i64,
    pub anchor: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExtractFragmentResultDto {
    pub fragment_data: String,
    pub plain_text: String,
}
