// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::BlockInfoDto;
use crate::GetBlockAtPositionDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Block, Document, Frame, InlineElement};
use common::types::EntityId;

pub trait GetBlockAtPositionUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GetBlockAtPositionUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/get_block_at_position_uow.rs
//
#[macros::uow_action(entity = "Document", action = "GetRO")]
#[macros::uow_action(entity = "Document", action = "GetMultiRO")]
#[macros::uow_action(entity = "Frame", action = "GetRO")]
#[macros::uow_action(entity = "Frame", action = "GetMultiRO")]
#[macros::uow_action(entity = "Block", action = "GetRO")]
#[macros::uow_action(entity = "Block", action = "GetMultiRO")]
#[macros::uow_action(entity = "InlineElement", action = "GetRO")]
#[macros::uow_action(entity = "InlineElement", action = "GetMultiRO")]
pub trait GetBlockAtPositionUnitOfWorkTrait: QueryUnitOfWork {}

pub struct GetBlockAtPositionUseCase {
    uow_factory: Box<dyn GetBlockAtPositionUnitOfWorkFactoryTrait>,
}

impl GetBlockAtPositionUseCase {
    pub fn new(uow_factory: Box<dyn GetBlockAtPositionUnitOfWorkFactoryTrait>) -> Self {
        GetBlockAtPositionUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &GetBlockAtPositionDto) -> Result<BlockInfoDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: GetBlockAtPositionUseCase to be implemented
        unimplemented!("GetBlockAtPositionUseCase unimplemented");
        uow.end_transaction()?;
        //Ok(BlockInfoDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
