// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::DocumentStatsDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Block, Document, Frame, InlineElement, List};
use common::types::EntityId;

pub trait GetDocumentStatsUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GetDocumentStatsUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/get_document_stats_uow.rs
//
#[macros::uow_action(entity = "Document", action = "GetRO")]
#[macros::uow_action(entity = "Document", action = "GetMultiRO")]
#[macros::uow_action(entity = "Frame", action = "GetRO")]
#[macros::uow_action(entity = "Frame", action = "GetMultiRO")]
#[macros::uow_action(entity = "Block", action = "GetRO")]
#[macros::uow_action(entity = "Block", action = "GetMultiRO")]
#[macros::uow_action(entity = "InlineElement", action = "GetRO")]
#[macros::uow_action(entity = "InlineElement", action = "GetMultiRO")]
#[macros::uow_action(entity = "List", action = "GetRO")]
#[macros::uow_action(entity = "List", action = "GetMultiRO")]
pub trait GetDocumentStatsUnitOfWorkTrait: QueryUnitOfWork {}

pub struct GetDocumentStatsUseCase {
    uow_factory: Box<dyn GetDocumentStatsUnitOfWorkFactoryTrait>,
}

impl GetDocumentStatsUseCase {
    pub fn new(uow_factory: Box<dyn GetDocumentStatsUnitOfWorkFactoryTrait>) -> Self {
        GetDocumentStatsUseCase { uow_factory }
    }

    pub fn execute(&mut self) -> Result<DocumentStatsDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: GetDocumentStatsUseCase to be implemented
        unimplemented!("GetDocumentStatsUseCase unimplemented");
        uow.end_transaction()?;
        //Ok(DocumentStatsDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
