// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::InsertFormattedTextDto;
use crate::InsertFormattedTextResultDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Block, Document, Frame, InlineElement};
use common::types::EntityId;

pub trait InsertFormattedTextUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn InsertFormattedTextUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update, UpdateMulti, remove,
// removeMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/insert_formatted_text_uow.rs
//
#[macros::uow_action(entity = "Document", action = "Get")]
#[macros::uow_action(entity = "Document", action = "GetMulti")]
#[macros::uow_action(entity = "Document", action = "Snapshot")]
#[macros::uow_action(entity = "Document", action = "Restore")]
#[macros::uow_action(entity = "Frame", action = "Get")]
#[macros::uow_action(entity = "Frame", action = "GetMulti")]
#[macros::uow_action(entity = "Frame", action = "Snapshot")]
#[macros::uow_action(entity = "Frame", action = "Restore")]
#[macros::uow_action(entity = "Block", action = "Get")]
#[macros::uow_action(entity = "Block", action = "GetMulti")]
#[macros::uow_action(entity = "Block", action = "Snapshot")]
#[macros::uow_action(entity = "Block", action = "Restore")]
#[macros::uow_action(entity = "InlineElement", action = "Get")]
#[macros::uow_action(entity = "InlineElement", action = "GetMulti")]
#[macros::uow_action(entity = "InlineElement", action = "Snapshot")]
#[macros::uow_action(entity = "InlineElement", action = "Restore")]
pub trait InsertFormattedTextUnitOfWorkTrait: CommandUnitOfWork {}

pub struct InsertFormattedTextUseCase {
    uow_factory: Box<dyn InsertFormattedTextUnitOfWorkFactoryTrait>,
}

impl InsertFormattedTextUseCase {
    pub fn new(uow_factory: Box<dyn InsertFormattedTextUnitOfWorkFactoryTrait>) -> Self {
        InsertFormattedTextUseCase { uow_factory }
    }

    pub fn execute(
        &mut self,
        dto: &InsertFormattedTextDto,
    ) -> Result<InsertFormattedTextResultDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: InsertFormattedTextUseCase to be implemented
        unimplemented!("InsertFormattedTextUseCase unimplemented");
        uow.commit()?;
        //Ok(InsertFormattedTextResultDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
use common::undo_redo::UndoRedoCommand;
use std::any::Any;
impl UndoRedoCommand for InsertFormattedTextUseCase {
    fn undo(&mut self) -> Result<()> {
        //TODO: InsertFormattedTextUseCase  undo to be implemented
        unimplemented!("InsertFormattedTextUseCase undo unimplemented");

        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        //TODO: InsertFormattedTextUseCase  redo to be implemented
        unimplemented!("InsertFormattedTextUseCase redo unimplemented");

        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
