// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::ExportMarkdownDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Block, Document, Frame, InlineElement, List};
use common::types::EntityId;

pub trait ExportMarkdownUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn ExportMarkdownUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/export_markdown_uow.rs
//
#[macros::uow_action(entity = "Document", action = "GetRO")]
#[macros::uow_action(entity = "Document", action = "GetMultiRO")]
#[macros::uow_action(entity = "Frame", action = "GetRO")]
#[macros::uow_action(entity = "Frame", action = "GetMultiRO")]
#[macros::uow_action(entity = "Block", action = "GetRO")]
#[macros::uow_action(entity = "Block", action = "GetMultiRO")]
#[macros::uow_action(entity = "InlineElement", action = "GetRO")]
#[macros::uow_action(entity = "InlineElement", action = "GetMultiRO")]
#[macros::uow_action(entity = "List", action = "GetRO")]
#[macros::uow_action(entity = "List", action = "GetMultiRO")]
pub trait ExportMarkdownUnitOfWorkTrait: QueryUnitOfWork {}

pub struct ExportMarkdownUseCase {
    uow_factory: Box<dyn ExportMarkdownUnitOfWorkFactoryTrait>,
}

impl ExportMarkdownUseCase {
    pub fn new(uow_factory: Box<dyn ExportMarkdownUnitOfWorkFactoryTrait>) -> Self {
        ExportMarkdownUseCase { uow_factory }
    }

    pub fn execute(&mut self) -> Result<ExportMarkdownDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: ExportMarkdownUseCase to be implemented
        unimplemented!("ExportMarkdownUseCase unimplemented");
        uow.end_transaction()?;
        //Ok(ExportMarkdownDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
