// Generated by Qleany v1.4.8 from feature_use_case_uow.tera

use crate::use_cases::get_block_at_position_uc::{
    GetBlockAtPositionUnitOfWorkFactoryTrait, GetBlockAtPositionUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{Block, Document, Frame, Root};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;

// Unit of work for GetBlockAtPosition

pub struct GetBlockAtPositionUnitOfWork {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
}

impl GetBlockAtPositionUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        GetBlockAtPositionUnitOfWork {
            context: db_context.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for GetBlockAtPositionUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction.take().unwrap().end_read_transaction()?;
        Ok(())
    }
}

#[macros::uow_action(entity = "Root", action = "GetRO")]
#[macros::uow_action(entity = "Root", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Document", action = "GetRO")]
#[macros::uow_action(entity = "Document", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Frame", action = "GetRO")]
#[macros::uow_action(entity = "Frame", action = "GetMultiRO")]
#[macros::uow_action(entity = "Frame", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Block", action = "GetRO")]
#[macros::uow_action(entity = "Block", action = "GetMultiRO")]
impl GetBlockAtPositionUnitOfWorkTrait for GetBlockAtPositionUnitOfWork {}

pub struct GetBlockAtPositionUnitOfWorkFactory {
    context: DbContext,
}

impl GetBlockAtPositionUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        GetBlockAtPositionUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl GetBlockAtPositionUnitOfWorkFactoryTrait for GetBlockAtPositionUnitOfWorkFactory {
    fn create(&self) -> Box<dyn GetBlockAtPositionUnitOfWorkTrait> {
        Box::new(GetBlockAtPositionUnitOfWork::new(&self.context))
    }
}
