// Generated by Qleany v1.7.3 from common_entity_table.tera

// ═══════════════════════════════════════════════════════════════════════
// Leaf entity (no forward relationships) — macro implementation
// ═══════════════════════════════════════════════════════════════════════

use super::list_repository::ListTable;
use super::list_repository::ListTableRO;
use crate::entities::List;

crate::impl_leaf_entity_table!(
    entity: List,
    entity_name: "list",
    store_field: lists,
    table_trait: ListTable,
    table_ro_trait: ListTableRO,
    table_struct: ListHashMapTable,
    table_ro_struct: ListHashMapTableRO,
    backward_junctions: [

        (jn_list_from_block_list),
        (jn_list_from_document_lists),
    ],
);
