// Generated by Qleany v1.4.8 from frontend_feature_commands.tera

//! DocumentEditing feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use document_editing::{
    CreateListDto, CreateListResultDto, DeleteTextDto, DeleteTextResultDto, InsertBlockDto,
    InsertBlockResultDto, InsertFormattedTextDto, InsertFormattedTextResultDto, InsertFragmentDto,
    InsertFragmentResultDto, InsertFrameDto, InsertFrameResultDto, InsertHtmlAtPositionDto,
    InsertHtmlAtPositionResultDto, InsertImageDto, InsertImageResultDto, InsertListDto,
    InsertListResultDto, InsertMarkdownAtPositionDto, InsertMarkdownAtPositionResultDto,
    InsertTextDto, InsertTextResultDto, document_editing_controller,
};

pub fn insert_text(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertTextDto,
) -> Result<InsertTextResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_text(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_text")
}

pub fn delete_text(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &DeleteTextDto,
) -> Result<DeleteTextResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::delete_text(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("delete_text")
}

pub fn insert_block(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertBlockDto,
) -> Result<InsertBlockResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_block(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_block")
}

pub fn insert_image(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertImageDto,
) -> Result<InsertImageResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_image(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_image")
}

pub fn insert_frame(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertFrameDto,
) -> Result<InsertFrameResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_frame(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_frame")
}

pub fn insert_formatted_text(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertFormattedTextDto,
) -> Result<InsertFormattedTextResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_formatted_text(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_formatted_text")
}

pub fn create_list(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateListDto,
) -> Result<CreateListResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::create_list(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("create_list")
}

pub fn insert_list(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertListDto,
) -> Result<InsertListResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_list(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_list")
}

pub fn insert_fragment(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertFragmentDto,
) -> Result<InsertFragmentResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_fragment(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_fragment")
}

pub fn insert_html_at_position(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertHtmlAtPositionDto,
) -> Result<InsertHtmlAtPositionResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_html_at_position(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_html_at_position")
}

pub fn insert_markdown_at_position(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &InsertMarkdownAtPositionDto,
) -> Result<InsertMarkdownAtPositionResultDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    document_editing_controller::insert_markdown_at_position(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("insert_markdown_at_position")
}
