// Generated by Qleany v1.5.0 from common_entity_table.tera

use super::root_repository::RootRelationshipField;
use super::root_repository::RootTable;
use super::root_repository::RootTableRO;
use crate::database::Postcard;
use crate::entities::Root;
use crate::error::RepositoryError;
use crate::snapshot::{JunctionSnapshot, TableLevelSnapshot, TableSnapshot};
use crate::types::EntityId;
use redb::{ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const ROOT_TABLE: TableDefinition<EntityId, Postcard<Root>> = TableDefinition::new("root");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

const DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("document_from_root_document_junction");
// backward relationships

fn get_junction_table_definition(
    field: &'_ RootRelationshipField,
) -> TableDefinition<'_, EntityId, Vec<EntityId>> {
    match field {
        RootRelationshipField::Document => DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE,
    }
}

pub struct RootRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> RootRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        RootRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), RepositoryError> {
        transaction.open_table(ROOT_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;

        Ok(())
    }
}

impl<'a> RootTable for RootRedbTable<'a> {
    fn create(&mut self, entity: &Root) -> Result<Root, RepositoryError> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<Root>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &Root) -> Result<Root, RepositoryError> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update_with_relationships(&mut self, entity: &Root) -> Result<Root, RepositoryError> {
        let v = self.update_with_relationships_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn create_multi(&mut self, entities: &[Root]) -> Result<Vec<Root>, RepositoryError> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"root".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;

        let mut document_junction_table = self
            .transaction
            .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                Root {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if root_table.get(&entity.id)?.is_some() {
                    return Err(RepositoryError::DuplicateId {
                        entity: "Root",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            // one-to-one constraint check: ensure document is not already referenced by another root
            {
                let mut iter = document_junction_table.iter()?;
                while let Some(Ok((existing_id, right_ids))) = iter.next() {
                    let existing_id = existing_id.value();
                    if existing_id != new_entity.id
                        && right_ids.value().contains(&new_entity.document)
                    {
                        panic!(
                            "One-to-one constraint violation: Document {} is already referenced by Root {}",
                            new_entity.document, existing_id
                        );
                    }
                }
            }
            root_table.insert(new_entity.id, new_entity.clone())?;

            document_junction_table
                .insert(new_entity.id, vec![new_entity.document] as Vec<EntityId>)?;
            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("root".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Root>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        let document_junction_table = self
            .transaction
            .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = root_table.get(id)? {
                let mut entity = guard.value().clone();
                let mut _junction_complete = true;

                // get document from junction table
                match document_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop()
                {
                    Some(val) => entity.document = val,
                    None => {
                        log::warn!(
                            "Root {} has incomplete junction data (missing document), treating as not found",
                            id
                        );
                        _junction_complete = false;
                    }
                }
                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<Root>, RepositoryError> {
        let mut list = Vec::new();
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        let document_junction_table = self
            .transaction
            .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;

        let mut iter = root_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let id = id.value();
            let mut entity = data.value().clone();
            let mut _junction_complete = true;

            // get document from junction table
            match document_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop()
            {
                Some(val) => entity.document = val,
                None => {
                    log::warn!(
                        "Root {} has incomplete junction data (missing document), skipping",
                        id
                    );
                    _junction_complete = false;
                }
            }

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }

    // Scalar-only update: writes entity data to the main table but does NOT touch junction tables.
    // The serialized entity may contain stale/default relationship field values in the main table;
    // this is harmless because get_multi() always overlays fresh data from junction tables.
    // Use update_with_relationships_multi() to write both scalars and relationships.
    fn update_multi(&mut self, entities: &[Root]) -> Result<Vec<Root>, RepositoryError> {
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            root_table.insert(entity.id, entity)?;
        }
        drop(root_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[Root],
    ) -> Result<Vec<Root>, RepositoryError> {
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;

        let mut document_junction_table = self
            .transaction
            .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            // one-to-one constraint check: ensure document is not already referenced by another root
            {
                let mut iter = document_junction_table.iter()?;
                while let Some(Ok((existing_id, right_ids))) = iter.next() {
                    let existing_id = existing_id.value();
                    if existing_id != entity.id && right_ids.value().contains(&entity.document) {
                        panic!(
                            "One-to-one constraint violation: Document {} is already referenced by Root {}",
                            entity.document, existing_id
                        );
                    }
                }
            }
            root_table.insert(entity.id, entity)?;

            document_junction_table.insert(entity.id, vec![entity.document] as Vec<EntityId>)?;
        }
        drop(root_table);
        drop(document_junction_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;

        // forward relationships

        let mut document_junction_table = self
            .transaction
            .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;

        // backward relationships

        for id in ids {
            root_table.remove(id)?;

            document_junction_table.remove(id)?;
        }
        Ok(())
    }
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &RootRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut map = std::collections::HashMap::new();
        for id in ids {
            let right_ids = table
                .get(id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            map.insert(*id, right_ids);
        }
        Ok(map)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
    ) -> Result<usize, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        Ok(table.get(id)?.map(|g| g.value().len()).unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let all = table
            .get(id)?
            .map(|g| g.value().clone())
            .unwrap_or_default();
        Ok(all.into_iter().skip(offset).take(limit).collect())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &RootRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }

    fn set_relationship_multi(
        &mut self,
        field: &RootRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), RepositoryError> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        for (left_id, entities) in relationships {
            table.insert(left_id, entities)?;
        }
        Ok(())
    }

    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &RootRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(*id, right_ids.to_vec())?;
        Ok(())
    }

    fn move_relationship_ids(
        &mut self,
        id: &EntityId,
        field: &RootRelationshipField,
        ids_to_move: &[EntityId],
        new_index: i32,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        if ids_to_move.is_empty() {
            return self.get_relationship(id, field);
        }
        let current_ids = self.get_relationship(id, field)?;
        let move_set: std::collections::HashSet<EntityId> = ids_to_move.iter().copied().collect();
        let mut remaining: Vec<EntityId> = current_ids
            .into_iter()
            .filter(|eid| !move_set.contains(eid))
            .collect();
        let insert_pos = if new_index < 0 || (new_index as usize) > remaining.len() {
            remaining.len()
        } else {
            new_index as usize
        };
        for (i, &eid) in ids_to_move.iter().enumerate() {
            remaining.insert(insert_pos + i, eid);
        }
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(*id, remaining.clone())?;
        Ok(remaining)
    }

    fn snapshot_rows(&self, ids: &[EntityId]) -> Result<TableLevelSnapshot, RepositoryError> {
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        // Snapshot entity rows as postcard bytes
        let mut rows = Vec::new();
        for id in ids {
            if let Some(guard) = root_table.get(id)? {
                let entity = guard.value();
                let bytes = postcard::to_allocvec(&entity)
                    .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
                rows.push((*id, bytes));
            }
        }

        // Snapshot forward junction tables
        let mut forward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "document_from_root_document_junction".to_string(),
                entries,
            });
        }

        // Snapshot backward junction tables (entries that reference any of the given ids)
        let backward_junctions = Vec::new();

        Ok(TableLevelSnapshot {
            entity_rows: TableSnapshot {
                table_name: "root".to_string(),
                rows,
            },
            forward_junctions,
            backward_junctions,
        })
    }

    fn restore_rows(&mut self, snap: &TableLevelSnapshot) -> Result<(), RepositoryError> {
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;

        // Restore entity rows from postcard bytes (redb insert is upsert)
        for (id, bytes) in &snap.entity_rows.rows {
            let entity: Root = postcard::from_bytes(bytes)
                .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
            root_table.insert(*id, entity)?;
        }

        // Restore forward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "document_from_root_document_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        // Restore backward junction entries

        Ok(())
    }
}

pub struct RootRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> RootRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        RootRedbTableRO { transaction }
    }
}

impl<'a> RootTableRO for RootRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Root>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Root>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        let document_junction_table = self
            .transaction
            .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = root_table.get(id)? {
                let mut entity = guard.value().clone();
                let mut _junction_complete = true;

                // get document from junction table
                match document_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop()
                {
                    Some(val) => entity.document = val,
                    None => {
                        log::warn!(
                            "Root {} has incomplete junction data (missing document), treating as not found",
                            id
                        );
                        _junction_complete = false;
                    }
                }
                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<Root>, RepositoryError> {
        let mut list = Vec::new();
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        let document_junction_table = self
            .transaction
            .open_table(DOCUMENT_FROM_ROOT_DOCUMENT_JUNCTION_TABLE)?;

        let mut iter = root_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let id = id.value();
            let mut entity = data.value().clone();
            let mut _junction_complete = true;

            // get document from junction table
            match document_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop()
            {
                Some(val) => entity.document = val,
                None => {
                    log::warn!(
                        "Root {} has incomplete junction data (missing document), skipping",
                        id
                    );
                    _junction_complete = false;
                }
            }

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &RootRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut map = std::collections::HashMap::new();
        for id in ids {
            let right_ids = table
                .get(id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            map.insert(*id, right_ids);
        }
        Ok(map)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
    ) -> Result<usize, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        Ok(table.get(id)?.map(|g| g.value().len()).unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let all = table
            .get(id)?
            .map(|g| g.value().clone())
            .unwrap_or_default();
        Ok(all.into_iter().skip(offset).take(limit).collect())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &RootRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }
}
