// Generated by Qleany v1.5.0 from entity_controller.tera

use super::{
    dtos::{CreateDocumentDto, DocumentDto, UpdateDocumentDto},
    units_of_work::{DocumentReadUoWFactory, DocumentWriteUoWFactory},
};
use crate::DocumentRelationshipDto;
use anyhow::{Ok, Result};
use common::direct_access::document::DocumentRelationshipField;
use common::direct_access::use_cases;
use common::undo_redo::UndoRedoManager;
use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create_orphan(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &CreateDocumentDto,
) -> Result<DocumentDto> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::UndoableCreateOrphanUseCase::new(uow_factory);
    let entity_in: common::entities::Document = entity.into();
    let result = uc.execute(&entity_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into())
}

pub fn create_orphan_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[CreateDocumentDto],
) -> Result<Vec<DocumentDto>> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Document> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UndoableCreateOrphanUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &CreateDocumentDto,
    owner_id: EntityId,
    index: i32,
) -> Result<DocumentDto> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::Document = entity.into();
    let strategy = use_cases::OwnerStrategy::Replacing;
    let mut uc = use_cases::UndoableCreateUseCase::new(uow_factory, strategy);
    let result = uc.execute(&entity_in, owner_id, index)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into())
}

pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[CreateDocumentDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<DocumentDto>> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Document> =
        entities.iter().map(|dto| dto.into()).collect();
    let strategy = use_cases::OwnerStrategy::Replacing;
    let mut uc = use_cases::UndoableCreateUseCase::new(uow_factory, strategy);
    let result = uc.execute_multi(&entities_in, owner_id, index)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<DocumentDto>> {
    let uow_factory = DocumentReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute(id)?.map(|e| e.into()))
}

pub fn get_all(db_context: &DbContext) -> Result<Vec<DocumentDto>> {
    let uow_factory = DocumentReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute_all()?.into_iter().map(|e| e.into()).collect())
}

pub fn get_multi(db_context: &DbContext, ids: &[EntityId]) -> Result<Vec<Option<DocumentDto>>> {
    let uow_factory = DocumentReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc
        .execute_multi(ids)?
        .into_iter()
        .map(|o| o.map(|e| e.into()))
        .collect())
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &UpdateDocumentDto,
) -> Result<DocumentDto> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::Document = entity.into();
    let mut uc = use_cases::UndoableUpdateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into())
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[UpdateDocumentDto],
) -> Result<Vec<DocumentDto>> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Document> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UndoableUpdateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn update_with_relationships(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &DocumentDto,
) -> Result<DocumentDto> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::Document = entity.into();
    let mut uc = use_cases::UndoableUpdateWithRelationshipsUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into())
}

pub fn update_with_relationships_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[DocumentDto],
) -> Result<Vec<DocumentDto>> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Document> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UndoableUpdateWithRelationshipsUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn remove(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    id: &EntityId,
) -> Result<()> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::UndoableRemoveUseCase::new(uow_factory);
    uc.execute(id)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::UndoableRemoveUseCase::new(uow_factory);
    uc.execute_multi(ids)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn get_relationship(
    db_context: &DbContext,
    id: &EntityId,
    field: &DocumentRelationshipField,
) -> Result<Vec<EntityId>> {
    let uow_factory = DocumentReadUoWFactory::new(db_context);
    let uc = use_cases::GetRelationshipUseCase::<DocumentRelationshipField, _>::new(uow_factory);
    uc.execute(id, field)
}

pub fn get_relationship_many(
    db_context: &DbContext,
    ids: &[EntityId],
    field: &DocumentRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    let uow_factory = DocumentReadUoWFactory::new(db_context);
    let uc =
        use_cases::GetRelationshipManyUseCase::<DocumentRelationshipField, _>::new(uow_factory);
    uc.execute(ids, field)
}

pub fn get_relationship_count(
    db_context: &DbContext,
    id: &EntityId,
    field: &DocumentRelationshipField,
) -> Result<usize> {
    let uow_factory = DocumentReadUoWFactory::new(db_context);
    let uc =
        use_cases::GetRelationshipCountUseCase::<DocumentRelationshipField, _>::new(uow_factory);
    uc.execute(id, field)
}

pub fn get_relationship_in_range(
    db_context: &DbContext,
    id: &EntityId,
    field: &DocumentRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    let uow_factory = DocumentReadUoWFactory::new(db_context);
    let uc =
        use_cases::GetRelationshipInRangeUseCase::<DocumentRelationshipField, _>::new(uow_factory);
    uc.execute(id, field, offset, limit)
}

pub fn set_relationship(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &DocumentRelationshipDto,
) -> Result<()> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let mut uc =
        use_cases::UndoableSetRelationshipUseCase::<DocumentRelationshipField, _>::new(uow_factory);
    uc.execute(&dto.id, &dto.field, dto.right_ids.as_slice())?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn move_relationship(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    id: &EntityId,
    field: &DocumentRelationshipField,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Result<Vec<EntityId>> {
    let uow_factory = DocumentWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::UndoableMoveRelationshipUseCase::<DocumentRelationshipField, _>::new(
        uow_factory,
    );
    let result = uc.execute(id, field, ids_to_move, new_index)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}
