// Generated by Qleany v1.4.8 from feature_use_case_uow.tera

use crate::use_cases::export_plain_text_uc::{
    ExportPlainTextUnitOfWorkFactoryTrait, ExportPlainTextUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{Block, Document, Frame, Root};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;

// Unit of work for ExportPlainText

pub struct ExportPlainTextUnitOfWork {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
}

impl ExportPlainTextUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        ExportPlainTextUnitOfWork {
            context: db_context.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for ExportPlainTextUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction.take().unwrap().end_read_transaction()?;
        Ok(())
    }
}

#[macros::uow_action(entity = "Root", action = "GetRO")]
#[macros::uow_action(entity = "Root", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Document", action = "GetRO")]
#[macros::uow_action(entity = "Document", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Frame", action = "GetRO")]
#[macros::uow_action(entity = "Frame", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Block", action = "GetMultiRO")]
impl ExportPlainTextUnitOfWorkTrait for ExportPlainTextUnitOfWork {}

pub struct ExportPlainTextUnitOfWorkFactory {
    context: DbContext,
}

impl ExportPlainTextUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        ExportPlainTextUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl ExportPlainTextUnitOfWorkFactoryTrait for ExportPlainTextUnitOfWorkFactory {
    fn create(&self) -> Box<dyn ExportPlainTextUnitOfWorkTrait> {
        Box::new(ExportPlainTextUnitOfWork::new(&self.context))
    }
}
