// Generated by Qleany v1.4.8 from feature_use_case_uow.tera

use crate::use_cases::import_html_uc::{
    ImportHtmlUnitOfWorkFactoryTrait, ImportHtmlUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::CommandUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{Block, Document, Frame, InlineElement, List, Resource, Root};
use common::event::{AllEvent, DirectAccessEntity, Event, EventBuffer, EventHub, Origin};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::sync::Arc;
use std::sync::Mutex;

pub struct ImportHtmlUnitOfWork {
    context: DbContext,
    transaction: Mutex<Option<Transaction>>,
    event_hub: Arc<EventHub>,
    event_buffer: Mutex<EventBuffer>,
}

impl ImportHtmlUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        ImportHtmlUnitOfWork {
            context: db_context.clone(),
            transaction: Mutex::new(None),
            event_hub: event_hub.clone(),
            event_buffer: Mutex::new(EventBuffer::new()),
        }
    }
}

impl CommandUnitOfWork for ImportHtmlUnitOfWork {
    fn begin_transaction(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        *transaction = Some(Transaction::begin_write_transaction(&self.context)?);
        self.event_buffer.lock().unwrap().begin_buffering();
        Ok(())
    }

    fn commit(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction.take().unwrap().commit()?;
        drop(transaction); // release lock before flushing events
        for event in self.event_buffer.lock().unwrap().flush() {
            self.event_hub.send_event(event);
        }
        Ok(())
    }

    fn rollback(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction.take().unwrap().rollback()?;
        drop(transaction);
        self.event_buffer.lock().unwrap().discard();
        Ok(())
    }

    fn create_savepoint(&self) -> Result<types::Savepoint> {
        let transaction = self.transaction.lock().unwrap();
        transaction.as_ref().unwrap().create_savepoint()
    }

    fn restore_to_savepoint(&mut self, savepoint: types::Savepoint) -> Result<()> {
        let mut transaction_guard = self.transaction.lock().unwrap();
        let mut transaction = transaction_guard.take().unwrap();
        transaction.restore_to_savepoint(savepoint)?;

        // Discard buffered events — savepoint restore invalidated them
        self.event_buffer.lock().unwrap().discard();

        // Send Reset immediately (not buffered — UI must refresh now)
        self.event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::All(AllEvent::Reset)),
            ids: vec![],
            data: None,
        });

        *transaction_guard = Some(transaction);

        Ok(())
    }
}
//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update, UpdateMulti, remove,  removeMulti, GetRelationship,
// GetRelationshipsFromRightIds, SetRelationship, SetRelationshipMulti, Snapshot, Restore
//
// You have here a long operation read-write unit of work.
//
// RO means Read Only, so *RO actions should not used be here.
// Don't forget to set thread_safe = true for long operation's unit of work.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/import_html_uc.rs
//
#[macros::uow_action(entity = "Root", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Root", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Root", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "Root", action = "Restore", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "Restore", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "Restore", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "Restore", thread_safe = true)]
#[macros::uow_action(entity = "InlineElement", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "InlineElement", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "InlineElement", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "InlineElement", action = "Restore", thread_safe = true)]
#[macros::uow_action(entity = "List", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "List", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "List", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "List", action = "Restore", thread_safe = true)]
#[macros::uow_action(entity = "Resource", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Resource", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Resource", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "Resource", action = "Restore", thread_safe = true)]
impl ImportHtmlUnitOfWorkTrait for ImportHtmlUnitOfWork {}

pub struct ImportHtmlUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl ImportHtmlUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        ImportHtmlUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl ImportHtmlUnitOfWorkFactoryTrait for ImportHtmlUnitOfWorkFactory {
    fn create(&self) -> Box<dyn ImportHtmlUnitOfWorkTrait> {
        Box::new(ImportHtmlUnitOfWork::new(&self.context, &self.event_hub))
    }
}
